server:
  port : 5000
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://{database}}:3306/board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: {username}
    password: {password}